### ISSUE TITLE
{\"label\":\"INVALID_SIGNATURE\",\"message\":\"Signature mismatch\"}\n"}

### ISSUE THREAD

**Issue by qs-lll** [gateio/WebSocket-API#13]
{\"label\":\"INVALID_SIGNATURE\",\"message\":\"Signature mismatch\"}\n"}

为什么总提示这个呀 api key sign 都是正确的

**Comment by revilwang** [comment]
请提供更多的信息，包括：
1. 具体对接的 WebSocket 服务地址
2. 使用的 APIv2 还是 APIv4 的 API Key
3. 具体的验签方式

**Comment by qs-lll** [comment]
api v4  futures.liquidates

**Comment by revilwang** [comment]
1，3 的信息仍然缺失

**Comment by qs-lll** [comment]
1."wss://fx-ws-testnet.gateio.ws/v4/ws/btc"
3.验签? 
![image](https://user-images.githubusercontent.com/5264241/115192845-ee5b0c80-a11d-11eb-9fc0-708612ec7a9b.png)

**Comment by qs-lll** [comment]
{"time":1618814823,"channel":"futures.liquidates","event":"subscribe","error":{"code":2,"message":"http get status code err, status : 400, url : http://127.0.0.1:8130/ws_auth, info : {\"label\":\"INVALID_SIGNATURE\",\"message\":\"Signature mismatch\"}\n"},"result":{"status":"failed"}}

**Comment by revilwang** [comment]
testnet 的 API Key 与实盘是独立的，请确认用的 API Key 是否是模拟合约的 API Key。另外，合约 WebSocket 支持移步新的仓库 [gatews](https://github.com/gateio/gatews)

**Comment by revilwang** [comment]
请提供具体的请求验签代码片段

**Comment by qs-lll** [comment]
使用的是正式环境, 异常返回值你看一下

**Comment by revilwang** [comment]
wss://fx-ws-testnet.gateio.ws/v4/ws/btc 是模拟合约地址。请提供具体验签代码片段，目前提供的信息只能认定是客户端自己的验签逻辑有问题

**Comment by qs-lll** [comment]
Please check the mail
