### ISSUE TITLE
websocket只支持spot的吗？

### ISSUE THREAD

**Issue by HFLeon** [gateio/WebSocket-API#17]
websocket的usertrades是否支持margin  cross_margin

**Comment by revilwang** [comment]
margin 的支持，cross_margin 暂时还不行。

后者的我们也安排增加一下

**Comment by HFLeon** [comment]
支持cross_margin的什么时候上线呢，这个需求比较紧急

**Comment by revilwang** [comment]
这个我们尽快安排加一下，的确是遗漏的部分

**Comment by HFLeon** [comment]
好的，等你们好消息

**Comment by HFLeon** [comment]
PC页面上操作的逐仓交易撤单，这边spot.usertrades没收到通知呢

**Comment by revilwang** [comment]
spot.usertrades 只推送成交，如果你订阅 spot.orders ，撤单的时候应该是会收到推送的

**Comment by HFLeon** [comment]
> 这个我们尽快安排加一下，的确是遗漏的部分

这部分发布了麻烦在这里通知一下哈，谢谢

**Comment by HFLeon** [comment]
今天会发布该特性吗

**Comment by revilwang** [comment]
`spot.orders` 和 `spot.usertrades` 目前已增加对全仓下单和成交的推送

**Comment by HFLeon** [comment]
好的，辛苦~
