### ISSUE TITLE
server.sign接口返回错误

### ISSUE THREAD

**Issue by heroWang** [gateio/WebSocket-API#2]
我跑的nodejs的例子程序.
server.sign方法返回报错:
`{"error": {"code": 11, "message": "Invalid timestamp."}, "result": null, "id": 973}`

key和secret用的我自己的. 请确认一下是否是bug或者是配置问题?

**Comment by KiriyaMirai** [comment]
我也遇到过这种问题，把win10里面自动设置时间打开同步了下系统的时间就好了

**Comment by heroWang** [comment]
@KiriyaMirai 是的,是系统时间问题.谢谢

**Comment by KiriyaMirai** [comment]
O(∩_∩)O
