### ISSUE TITLE
nodejs调用报错Error: certificate has expired

### ISSUE THREAD

**Issue by tangciwei** [gateio/WebSocket-API#7]
nodejs调用报这个错Error: certificate has expired

**Comment by suspended** [comment]
This repo is no longer maintained by Gate

**Comment by npomfret** [comment]
This is happening again - anyone know how to contact someone **useful** at gate.io?

**Comment by YueminHu** [comment]
i encountered error 'invalid timestamp' when using 'server.sign' call. even in their demo.
gonna ask for the customer service if they can provide something useful

**Comment by YueminHu** [comment]
> i encountered error 'invalid timestamp' when using 'server.sign' call. even in their demo.
> gonna ask for the customer service if they can provide something useful

its my system's time inaccuracy causing this problem
ummmm....never thought of that...🤣
